[package]
name = "sputter"
version = "0.1.1"
repository = "https://github.com/a222red/Sputter"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
